CREATE TABLE IF NOT EXISTS training_evaluations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NOT NULL,
  trainee_name VARCHAR(255) NULL,
  office_service_division VARCHAR(255) NULL,
  training_program VARCHAR(255) NOT NULL,
  topic VARCHAR(255) NULL,
  date_of_conduct DATE NOT NULL,
  venue VARCHAR(255) NOT NULL,
  training_objectives TEXT NULL,
  ratings_json LONGTEXT NULL,
  yesno_json LONGTEXT NULL,
  comments_1 TEXT NULL,
  comments_2 TEXT NULL,
  comments_3 TEXT NULL,
  level2_q1 LONGTEXT NULL,
  level2_q2 LONGTEXT NULL,
  level3_q1 LONGTEXT NULL,
  level3_q2 LONGTEXT NULL,
  level3_q3 LONGTEXT NULL,
  evaluated_by VARCHAR(255) NULL,
  evaluated_by_date DATE NULL,
  received_by VARCHAR(255) NULL,
  received_by_date DATE NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_course (user_id, course_id)
);
